### ISSUE TITLE
gRPC failure when deploying smart contract and other misc bugs

### ISSUE THREAD

**Issue by AnBapDan** [hashgraph/hedera-local-node#358] opened 2023-07-10 15:58 UTC
### Description

Hello, I am trying to integrate a DLT solution, in this case, Hashgraph, to achieve different metrics and evaluate different approaches.
That being said, I'm trying to evaluate different money exchange alternatives between IoT devices.

I'm using the npm version of Hedera Local Node to deploy a dev node on a VM to easily control flows and retrieve various metrics. 
(Node version: v18.16.0: npm: v9.5.1) 

However, it seems that this node sometimes does not accept incoming connections, mostly GRPC ones. 
1) When trying to deploy a smart contract, 90% of the time I got either connection timeout or not a healthy node.

2) When deploying a transaction, it seems successful, I can query it easily, but, running the exact same code to query a transaction at a later time, it seems that it cannot reach the transaction.

I developed a workaround by querying via curl using the explorer embedded with that setup and it works. It mostly fails when querying via Hashgraph SDK.

Another curious thing is that I cannot have a client in an outside file and export it. Every time I execute something I have to manually instantiate the client (client.forNetwork()....)

3) Also, sometimes the node appears to be active when ' docker ps'  but graphana shows an Unknown state and interactions do not work. (This bug seems random so, at the moment, I cannot replicate it since manual hedera restart commands fix it)

4) Finally, the last thing worth noting is that, by default, the explorer node has a configuration of searching for localhost. When browsing from another device, if devnet is selected, it requests the searching computer for localhost instead of the VM itself.

It seems that most of these errors are only related to the local node since when doing this on testnet, Most of these errors are gone.

If someone could help me on solving the smart contract deployment and query issue, I appreciate it.

### Steps to reproduce

1) When trying to deploy a smart contract, the snippet code I used is: 

```typescript
import { AccountId, Client, ContractCreateFlow, PrivateKey } from '@hashgraph/sdk'
import fs from 'fs';
import path from "path";

const mirror = "XX.XXX.XX.XX:5600"
const node = { "XX.XXX.XX.XX:50211": new AccountId(3) };

async function deployContract(dir:string,memo:string){

    const contractBytecode = fs.readFileSync(
        path.join(__dirname, dir)
      );
    let manager = Client.forNetwork(node).setMirrorNetwork(mirror);

    manager.setOperator(
        AccountId.fromString("0.0.2"),
        PrivateKey.fromString(
          "302e020100300506032b65700422042091132178e72057a1d7528025956fe39b0b847f200ab59b2fdd367017f3087137"
        )

    );

   const contract = new ContractCreateFlow().setBytecode(contractBytecode).setContractMemo(memo);
   
   const txResponse = await contract.execute(manager);
   const receipt = await txResponse.getReceipt(manager)
   console.log(receipt.contractId)
}

deployContract('../../bin/contracts/test.bin','test')
```

2) For the transaction issue I used the following:

```typescript
const mirror = "XX.XXX.XX.XX:5600"
const node = { "XX.XXX.XX.XX:50211": new AccountId(3) };

async function receipt(id: string) {
  const ed25519_client = Client.forNetwork(node).setMirrorNetwork(mirror); 
  ed25519_client.setOperator(
    AccountId.fromString("0.0.1022"),
    PrivateKey.fromStringED25519("0xa608e2130a0a3cb34f86e757303c862bee353d9ab77ba4387ec084f881d420d4")
  );
  const transactionReceipt = await new TransactionReceiptQuery().setTransactionId(id).execute(ed25519_client)

  console.log(transactionReceipt.status.toString());

}

receipt('0.0.1022@1689003873.877345855')
```

For 4) the issue may be related to a config in the docker itself when parsing the IP localhost inside .env file.
```txt
### Mirror Node Explorer ###
VUE_APP_PRODUCT_NAME="Hedera Mirror Node Explorer"
VUE_APP_DOCUMENT_TITLE_PREFIX="Hedera"
VUE_APP_ENABLE_STAKING=true
VUE_APP_LOCAL_MIRROR_NODE_MENU_NAME=LOCALNET
VUE_APP_LOCAL_MIRROR_NODE_URL=http://localhost:5551/
```
(I already saw a change in the newest version from localhost to 127.0.0.1. Do not know if it fixes this bug or not)

### Additional context

Snippet 1) provides this error:
```bash
/home/dani/Documents/MsCThesis-Daniel/helpers/node_modules/@hashgraph/sdk/lib/Executable.cjs:679
    throw new Error(`max attempts of ${maxAttempts.toString()} was reached for request with last error being: ${persistentError != null ? persistentError.toString() : ""}`);
          ^
Error: max attempts of 10 was reached for request with last error being: GrpcServiceError: No connection established
    at TransactionReceiptQuery.execute (/home/dani/Documents/MsCThesis-Daniel/helpers/node_modules/@hashgraph/sdk/lib/Executable.cjs:679:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async TransactionResponse.getReceipt (/home/dani/Documents/MsCThesis-Daniel/helpers/node_modules/@hashgraph/sdk/lib/transaction/TransactionResponse.cjs:86:21)
    at async FileAppendTransaction.executeAll (/home/dani/Documents/MsCThesis-Daniel/helpers/node_modules/@hashgraph/sdk/lib/file/FileAppendTransaction.cjs:326:7)
    at async FileAppendTransaction.execute (/home/dani/Documents/MsCThesis-Daniel/helpers/node_modules/@hashgraph/sdk/lib/file/FileAppendTransaction.cjs:297:13)
    at async ContractCreateFlow.execute (/home/dani/Documents/MsCThesis-Daniel/helpers/node_modules/@hashgraph/sdk/lib/contract/ContractCreateFlow.cjs:375:7)
    at async deployContract (/home/dani/Documents/MsCThesis-Daniel/helpers/smartContracts/deploy.ts:25:23)
```

Snippet 2) Appears successful at first, but the exact same snippet at later stages gives an error:
```bash
┌──(dani㉿kali)-[~/Documents/tese/hashgraph/transaction]
└─$ ts-node example.ts
SUCCESS
^C
```
Within minutes the same exact code changes to this
```bash                                                                                                                                                                                       
┌──(dani㉿kali)-[~/Documents/tese/hashgraph/transaction]
└─$ ts-node example.ts
/home/dani/Documents/tese/node_modules/@hashgraph/sdk/lib/Executable.cjs:652
    throw new Error(`max attempts of ${maxAttempts.toString()} was reached for request with last error being: ${persistentError != null ? persistentError.toString() : ""}`);
          ^
Error: max attempts of 10 was reached for request with last error being: GrpcServiceError: No connection established
    at TransactionReceiptQuery.execute (/home/dani/Documents/tese/node_modules/@hashgraph/sdk/lib/Executable.cjs:652:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async receipt (/home/dani/Documents/tese/hashgraph/transaction/example.ts:40:30)
```

### Hedera network

other

### Version

v2.10.0

### Operating system

Linux

**Comment by georgi-l95** [comment] 2023-07-12 11:06
First, let's make sure that your local-node is running as expected. Try starting with `hedera start -d`, if you installed it globally or directly from the repo with `node cli.js start -d` and tell me what you see. Are there errors or you see generation of accounts ?
![image](https://github.com/hashgraph/hedera-local-node/assets/14980879/eb8ee222-9624-4d73-b629-0c098fa23e7a)

**Comment by AnBapDan** [comment] 2023-07-12 11:10
Hey @georgi-l95 , yes, in that phase nothing weird occurs. Either by using flag -d or interactively I see the account generation. Sometimes it takes a while when copying the configs but nothing too relevant

**Comment by georgi-l95** [comment] 2023-07-12 11:45
Okay, will try to reproduce it and get back to you. As far as I understand 1 and 2 are the big blockers for you, right ?

**Comment by AnBapDan** [comment] 2023-07-12 11:49
Exactly. 1. and 2. are the most needed features in my case

**Comment by georgi-l95** [comment] 2023-07-12 13:21
Hey @AnBapDan I'm not able to reproduce this, I've tried to replicate your code as much as possible. But contract is deploying everytime without issues.

```
async function main() {
    const mirror = "127.0.0.1:5600"
    const node = { "127.0.0.1:50211": new AccountId(3) };
    const contractBytecode = {
        "bytecode": "0x608060405234801561001057600080fd5b506040516105ef3803806105ef83398101604081905261002f91610119565b8051610042906000906020840190610080565b507fad181ee258ff92d26bf7ed2e6b571ef1cba3afc45f028b863b0f02adaffc2f068160405161007291906101c1565b60405180910390a150610275565b82805461008c90610224565b90600052602060002090601f0160209004810192826100ae57600085556100f4565b82601f106100c757805160ff19168380011785556100f4565b828001600101855582156100f4579182015b828111156100f45782518255916020019190600101906100d9565b50610100929150610104565b5090565b5b808211156101005760008155600101610105565b60006020828403121561012a578081fd5b81516001600160401b0380821115610140578283fd5b818401915084601f830112610153578283fd5b8151818111156101655761016561025f565b604051601f8201601f19908116603f0116810190838211818310171561018d5761018d61025f565b816040528281528760208487010111156101a5578586fd5b6101b68360208301602088016101f4565b979650505050505050565b60208152600082518060208401526101e08160408501602087016101f4565b601f01601f19169190910160400192915050565b60005b8381101561020f5781810151838201526020016101f7565b8381111561021e576000848401525b50505050565b600181811c9082168061023857607f821691505b6020821081141561025957634e487b7160e01b600052602260045260246000fd5b50919050565b634e487b7160e01b600052604160045260246000fd5b61036b806102846000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c8063a41368621461003b578063cfae321714610050575b600080fd5b61004e6100493660046101e7565b61006e565b005b6100586100bc565b6040516100659190610291565b60405180910390f35b805161008190600090602084019061014e565b507fad181ee258ff92d26bf7ed2e6b571ef1cba3afc45f028b863b0f02adaffc2f06816040516100b19190610291565b60405180910390a150565b6060600080546100cb906102e4565b80601f01602080910402602001604051908101604052809291908181526020018280546100f7906102e4565b80156101445780601f1061011957610100808354040283529160200191610144565b820191906000526020600020905b81548152906001019060200180831161012757829003601f168201915b5050505050905090565b82805461015a906102e4565b90600052602060002090601f01602090048101928261017c57600085556101c2565b82601f1061019557805160ff19168380011785556101c2565b828001600101855582156101c2579182015b828111156101c25782518255916020019190600101906101a7565b506101ce9291506101d2565b5090565b5b808211156101ce57600081556001016101d3565b6000602082840312156101f8578081fd5b813567ffffffffffffffff8082111561020f578283fd5b818401915084601f830112610222578283fd5b8135818111156102345761023461031f565b604051601f8201601f19908116603f0116810190838211818310171561025c5761025c61031f565b81604052828152876020848701011115610274578586fd5b826020860160208301379182016020019490945295945050505050565b6000602080835283518082850152825b818110156102bd578581018301518582016040015282016102a1565b818111156102ce5783604083870101525b50601f01601f1916929092016040019392505050565b600181811c908216806102f857607f821691505b6020821081141561031957634e487b7160e01b600052602260045260246000fd5b50919050565b634e487b7160e01b600052604160045260246000fdfea2646970667358221220314a8c4d4a37715b15fb47f47480c0448d43d47ef026fc313ce390fba442a3ee64736f6c63430008040033"
    }

    let manager = Client.forNetwork(node).setMirrorNetwork(mirror);

    manager.setOperator(
        AccountId.fromString("0.0.2"),
        PrivateKey.fromString(
          "302e020100300506032b65700422042091132178e72057a1d7528025956fe39b0b847f200ab59b2fdd367017f3087137"
        )

    );

   const contract = new ContractCreateFlow().setBytecode(contractBytecode.bytecode).setGas(10_000_000).setConstructorParameters(new ContractFunctionParameters().addString("hello"));
   
   const txResponse = await contract.execute(manager);
   const receipt = await txResponse.getReceipt(manager)
   console.log(receipt.contractId)
}
```

When local-node is started, can you check `http://localhost:5551/api/v1/blocks?limit=100&order=desc` and refresh several time to see if new block are generated ?

**Comment by AnBapDan** [comment] 2023-07-12 13:29
I don't know for sure if deploying from the same machine works like you did. I'm trying to do it from another host to the node and that could be the cause of the problem. At the same time I was checking for incoming requests to the VM hosting the node and it arrives, and that's where it seems weird. Sometimes I receive the timeout error, but it deploys it after a long delay. I am going to try to deploy from the same VM the node is hosted and see if it is successful...

**Comment by AnBapDan** [comment] 2023-07-12 14:00
Using the block generation endpoint, I can confirm a new block is being generated

**Comment by georgi-l95** [comment] 2023-07-12 14:17
Okay, that means local-node is indeed running and you're able to deploy using from within the VM. Issue seems to be that you can't connect to it outside of the VM. There is also envoy proxy running on 50213, you could try it. I'm also looking for solution, ping me if you resolve it in the mean time. Thank you.

**Comment by AnBapDan** [comment] 2023-07-12 18:24
@georgi-l95 could you try something for me?
Could you try to block your IPv6 routing?
I was investigating and may have found the root problem. 
127.0.0.1 may work because it is using the loopback interface from the node VM. There is no NAT/PAT translation for the outside network. 
When I was verifying the open ports on the node VM, using netstat -tulnp all the ports are listening to TCP6 protocol. Although all the devices on the network have IPv4 and IPv6 addresses, only IPv4 works. However, I'm working on a Research institute and IPv6 routing is blocked, so I cannot check this theory.

**Comment by AnBapDan** [comment] 2023-08-19 10:51
Hello, I made two ipv6 static routes between those VMs because they're on the same switch. The problem remains on all the other components since i cannot make ipv6 routes between them. Is there any reason why those ports are ipv6 exclusive?

**Comment by georgi-l95** [comment] 2023-10-13 08:34
Hey @AnBapDan not sure why they are exclusive, sorry for the late response also. But did you manage to solve this issue, is this issue fixed so that we can close it?

**Comment by AnBapDan** [comment] 2023-10-13 10:33
Hey, yes! Throughout the updates, those bugs appear to be fixed ! Clean install on newer bersions and everything work as intended.

**Comment by georgi-l95** [comment] 2023-10-13 12:24
Nice, glad to hear that. Closing for now, feel free to open again or open a new one if another issue comes up.

**Closed by georgi-l95** 2023-10-13 12:24 UTC
Labels: Bug
