### ISSUE TITLE
Discrepancies in behaviour between the hardhat and hedera local node

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-local-node#290] opened 2023-03-05 17:20 UTC
### Description

I have written a test script demonstrating discrepancies between the hardhat and hedera local nodes. The script contains the following test cases, which all pass on the hardhat local node but all fail on the hedera local node:

1. **should be able to deploy many SillyLargeContract in parallel** - hardhat deploys all contracts in parallel with unique `create1` addresses; the hedera local node fails firstly as the `eth_estimateGas` call fails and so the default `gasLimit` used(~305k) is insufficient; however even if a sufficient `gasLimit` override is passed as is done in the following test case (2.) still only a single contract is effectively deployed as the `create1` addresses for the "deployed" contracts are all the same; in addition to the transaction hashes being equal. This is probably due to the nonce(i.e. the account's tx count) being the same at the start of the parallel deployments. The hardhat local node likely adjusts to using the correct nonce and hence does not have this issue.
2. **should be able to deploy many SillyLargeContract in parallel with gas overrides** - explained above in (1.)
3. **should be able to call setManyGreetings function in parallel** - similar issue to (1.) but for contract call transactions instead of contract deploys.
4. **should be able to call setManyGreetings function in parallel with gas overrides** - similar issue to (1.) and (3.)
5. **should be able to deposit and withdraw from vault repeatedly and get correct balances** - for some reason fungible HTS token balances accessed via a contract that interacts with the the precompile(in this case the `HERC20Util` contract) or via the ERC20 interface are NOT consistently correct; specifically in the case of multiple HTS token transfers occurring within the same contract call. However, the balances retrieved from the core network node using the SDK's `AccountBalanceQuery` is consistently correct.

### Steps to reproduce

1. Checkout to the branch in [this PR](https://github.com/mshakeg/hedera-json-rpc-relay/pull/17)
2. Start the hardhat local node: `npm run hardhat-start`
3. Run the `./test/discrepancies.test.ts` script against the hardhat node: `npm run test:dis:hardhat_local` and observe ALL pass; test case (5.) is skipped as it contains contracts that depend on the hedera precompile contract not executable on the hardhat node.
4. Now start up the hedera local node(`npm run hedera-start`) run the same script against it: `npm run test:dis:local` and observe ALL fail! Test case (5.) logs to the console whenever a token balance retrieved from the network node does NOT equal the token balance retrieved via eth_calls to EITHER the `ERC20#balanceOf`  OR to the `HERC20Util#balanceOf` function.

### Hedera network

other

### Version

@hashgraph/hedera-local@2.5.1

### Operating system

None

**Comment by Nana-EC** [comment] 2023-03-09 01:15
Thanks @mshakeg 
Appreciate the detail.
We'll look into this and circle back

**Comment by Ivo-Yankov** [comment] 2023-03-10 17:36
Hi @mshakeg,

Regarding points 1 and 3 I don't think there is much we can do - it seems that those tests require a lot of gas.
For points 2 and 4 the issue is that when the second transaction is submitted it results in a "WRONG_NONCE" error in the `eth_sendRawTransaction` method. The relay handles that error by calculating the hash from the signed transaction and returns it as a result. Normally that is the desired behaviour, but here because both signed transactions are the same, the resulting hash is also the same - hence why the transacion receipts you see afterwords are duplicated.

We noticed that when the transaction results in such an error no `ContractResult` record is created in the Mirror node, and so it isn't possible to retrieve the receipt for that transaction. We plan on modifying `eth_sendRawTransaction` to throw an error in such cases instead of returning a hash, which cannot be used to get a receipt.

We are still investigating point 5.

**Comment by georgi-l95** [comment] 2023-05-15 16:02
Hey @mshakeg is this resolved? Do you still have some issues or we can close this one ?

**Comment by mshakeg** [comment] 2023-05-15 16:09
Hey @georgi-l95 point 5 is still not resolved as of 2.8.0, see [this comment](https://github.com/mshakeg/hedera-json-rpc-relay/pull/20#discussion_r1186825436) for more detail.

**Comment by georgi-l95** [comment] 2023-07-24 11:10
Hey @mshakeg is point 5 still not resolved for you ? Should be fixed with the latest version of the relay and local-node. Can you confirm, if it's fixed?

**Comment by mshakeg** [comment] 2023-07-25 10:28
Hey @georgi-l95 point 5 is still an issue on local-node@2.11.1

**Comment by georgi-l95** [comment] 2023-10-13 08:32
Hey @mshakeg is point 5 still an issue, if no we can close this issue, if yes, let's close it and open new clean one, only with this problem ?

**Comment by mshakeg** [comment] 2023-10-13 08:57
Hey @georgi-l95 I just confirmed that point 5 is still an issue on `@hashgraph/hedera-local@2.13.0`

**Comment by georgi-l95** [comment] 2023-10-13 09:21
Okay thanks for confirming 👍

**Comment by georgi-l95** [comment] 2024-04-02 09:04
Closing this issue, as all of them should be fixed. If they are not, please reopen in relay repo, as those are json-rpc-relay problems, not local-node ones.

**Closed by georgi-l95** 2024-04-02 09:04 UTC
Labels: Bug, P1, Limechain
