### ISSUE TITLE
local node intermittently returns stale contract state

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-local-node#294] opened 2023-03-10 08:20 UTC
### Description

This issue is similar to point (5.) in #290, but instead of returning invalid token balances, stale contract storage is returned.

Additionally, contract storage does not return valid data.

### Steps to reproduce

Note: This issue is intermittent and if you're unable to replicate it, try restarting your hedera local node.

1. Checkout to the branch in [this PR](https://github.com/mshakeg/hedera-json-rpc-relay/pull/18)
2. Run the `./test/deletable.test.ts` script against the hardhat node: `npm run test:d` and observe all test cases pass
3. Now run the script against the hedera local node; after starting up the hedera node run: `npm run test:d:local` and observe the first test case fails in BOTH iterations on the `doesDeletableExist not reset to false` assertion.

To demo the contract storage issue:
1. On the same branch run the `./test/storage-increaser.test.ts` script against the hardhat node: `npm run test:si` and observe the test case passes.
2. Now run the script against the hedera local node: `npm run test:si:local` and observe the test case fails.

### Hedera network

other

### Version

@hashgraph/hedera-local@2.5.1

### Operating system

None

**Comment by natanasow** [comment] 2023-04-03 07:27
@mshakeg Hello, 
- `deletable.test.ts` - It's not reproducible on my side, could try with the latest versions and ping us again
- `storage-increaser.test.ts` - The contract storage issue is due to a low gas limit provided. After several tests locally, here are the correct values that will be acceptable in your case.
```typescript
// 08 mil gas --- good - 352 | bad - 353
// 15 mil gas --- good - 662 | bad - 663
const increaseNumSpaces = getRandomNumber(100, 352);
await storageIncreaser.increaseStorage(increaseNumSpaces, {
  gasLimit: 8_000_000
});
 ```

**Comment by mshakeg** [comment] 2023-04-03 07:59
Hi @natanasow thanks for the feedback, I'll investigate further on my side. Is point (5.) of #290 at least reproducible on your end? I originally suspected it may be related to this issue.

**Comment by mshakeg** [comment] 2023-04-04 09:36
Hi @natanasow I just re-ran the 2 scripts on local-node@2.6.0 and the original issues outlined are still present.

1. `storage-increaser.test.ts` - why does the hardhat local node not revert with insufficient gas? Are there discrepancies in the OPCODE gas costs? And if so why is this?
2. `deletable.test.ts` - still runs fine on the hardhat local node, but still fails on the hedera local node.

**Comment by georgi-l95** [comment] 2023-05-15 16:03
Hey @mshakeg is this issue still relevant, do you still experience it ?

**Comment by mshakeg** [comment] 2023-05-15 16:11
Hey @georgi-l95 yes, as of 2.8.0 this is still an issue as [explained here](https://github.com/hashgraph/hedera-local-node/issues/294#issuecomment-1495654777)

**Comment by natanasow** [comment] 2023-06-21 12:58
@mshakeg With the described fine-tuning below, I successfully ran your tests against the Hedera local node.

1 - `storage-increaser.ts` - Nope, there shouldn't be any differences in opcodes

There are several differences between the hardhat local node and the hedera local node in your configuration:
- If you're using the hardhat local node, you're setting `blockGasLimit` to `0x1fffffffffffff` and `gas` to `1_000_000_000`. In that case, if you skip the `gasLimit` in tx, you will be able to use far more gas than permitted in the Ethereum mainnet or any other network. I ran 10 000 iterations on your storage update contract test and the call costs 244 mil gas.
- On the other side, the hedera local node is limited to `15_000_000` `blockGasLimit`, which causes your discrepancies.

Another "problem" with your tests is the random generator for spaces. The range is very big and every number above ~360 will fail due to the "Transaction ran out of gas" on both hardhat and Hedera local node. If you remove the hardcoded `gasLimit`, the tests against the hardhat node will succeed every time, because the gas will be set to `1_000_000_000`, but if you run them against the hedera local node, they will fail, because `blockGasLimit` is limited to `15_000_000`. Made some measurements and that's the result :point_down: 

N | hardhat gas | hedera gas
-- | -- | --
100 | 2_269_059 | 2_268_855
350 | 7_883_071 | 7_882_855
1000 | 22_479_471 |

**Solution: Hardcode max `increaseNumSpaces` to 350 to be able to fit in 8 mil gas.**

2 - `deletable.test.ts` - Due to the difference between the hardhat local provider and our JSON-RPC provider, that part of your code throws an exception because our relay reverted with reason :confused:
```typescript
await expect(deletableFactory.createDeletable2()).to.be.revertedWithoutReason();
````
Alternatively, you can check if the transaction is reverted (no matter with or without reason), and it should work.
```typescript
await expect(deletableFactory.createDeletable2()).to.be.reverted;
```

**Solution: Replace `.revertedWithoutReason()` with `.reverted` to match the differences between Hardhat Provider and JSON-RPC provider.**

**Comment by mshakeg** [comment] 2023-07-07 13:14
@natanasow thanks for investigating, and apologies for the late reply, been a bit unproductive lately.

1 - `storage-increaser.test.ts` - I agree with your assessment

2 - `deletable.test.ts` - I agree with your assessment, however it only pertains to the 2nd test case in the script and NOT the 1st i.e. `should be able to delete contract via Deletable#destroy()`

**Comment by natanasow** [comment] 2023-07-18 11:55
@mshakeg

Just run your tests again against the latest local node and `should be able to delete contract via Deletable#destroy()` works as expected, without any errors. The second test needs `.to.be.reverted` instead of `.to.be.revertedWithReason()` which I explained in the comment above. Could you run the tests again on your side, and feel free to share the results or your concerns?

**Comment by mshakeg** [comment] 2023-07-25 09:41
@natanasow I've updated to the latest node, and the test cases all pass, however I have to explicitly specify a gas override for every transaction, otherwise it uses 21_000, which is always insufficient. For some reason even if I specify a default `gas` of 5e6 on the [hardhat network config](https://hardhat.org/hardhat-runner/docs/config) level it still uses 21_000.

**Comment by georgi-l95** [comment] 2023-07-25 10:46
That sounds to me like the issue is not in local-node, but rather in the relay.

**Comment by georgi-l95** [comment] 2023-10-13 08:33
This should be fixed, by the latest changes in the relay. Closing this issue, if this still persist, please open an issue in the relay.

**Closed by georgi-l95** 2023-10-13 08:33 UTC
Labels: Bug

**Comment by mshakeg** [comment] 2023-10-13 08:38
@georgi-l95 I think this may still be an issue, if you try to run [this Tests CI](https://github.com/hashgraph/hedera-smart-contracts/blob/main/.github/workflows/tests.yml) you'll notice that some jobs fail intermittently and require re-runs until they eventually succeed.
