### ISSUE TITLE
HBAR Rate limit exceeded error

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-local-node#239] opened 2022-12-02 14:20 UTC
### Description

I'm getting the following error from the relay when running through a long test case in my project.

hardhat stack trace:
```
     [Request ID: 95e64258-c5e9-40f6-9cb9-849c8b56d7de] HBAR Rate limit exceeded
  ProviderError: HttpProviderError
      at HttpProvider.request (/Users/usr/dev/proj/node_modules/hardhat/src/internal/core/providers/http.ts:78:19)
      at LocalAccountsProvider._getNonce (/Users/usr/dev/proj/node_modules/hardhat/src/internal/core/providers/accounts.ts:230:51)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async LocalAccountsProvider.request (/Users/usr/dev/proj/node_modules/hardhat/src/internal/core/providers/accounts.ts:168:27)
      at async TracerWrapper.request (/Users/usr/dev/proj/node_modules/hardhat-tracer/src/wrapper.ts:36:16)
      at async EthersProviderWrapper.send (/Users/usr/dev/proj/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
```

json-rpc-relay container logs:
```
[2022-12-02 14:12:45.828 +0000] DEBUG (rpc-server/49 on dd64e5a2d258): [Request ID: 95e64258-c5e9-40f6-9cb9-849c8b56d7de] eth_getTransactionCount
[2022-12-02 14:12:45.829 +0000] TRACE (relay-eth/49 on dd64e5a2d258): [Request ID: 95e64258-c5e9-40f6-9cb9-849c8b56d7de] getTransactionCount(address=0x67d8d32e9bf1a9968a5ff53b87d777aa8ebbee69, blockNumOrTag=pending)
[2022-12-02 14:12:45.829 +0000] TRACE (relay-eth/49 on dd64e5a2d258): [Request ID: 95e64258-c5e9-40f6-9cb9-849c8b56d7de] blockNumber()
[2022-12-02 14:12:45.840 +0000] DEBUG (mirror-node/49 on dd64e5a2d258): [Request ID: 95e64258-c5e9-40f6-9cb9-849c8b56d7de] [GET] blocks?limit=1&order=desc 200 11 ms
[2022-12-02 14:12:45.852 +0000] TRACE (mirror-node/49 on dd64e5a2d258): [Request ID: 95e64258-c5e9-40f6-9cb9-849c8b56d7de] Retry delay 500 ms
[2022-12-02 14:12:46.356 +0000] TRACE (mirror-node/49 on dd64e5a2d258): [Request ID: 95e64258-c5e9-40f6-9cb9-849c8b56d7de] Retry delay 500 ms
[2022-12-02 14:12:46.863 +0000] TRACE (mirror-node/49 on dd64e5a2d258): [Request ID: 95e64258-c5e9-40f6-9cb9-849c8b56d7de] Retry delay 500 ms
[2022-12-02 14:12:47.369 +0000] DEBUG (mirror-node/49 on dd64e5a2d258): [Request ID: 95e64258-c5e9-40f6-9cb9-849c8b56d7de] [GET] contracts/0x67d8d32e9bf1a9968a5ff53b87d777aa8ebbee69 404 status
[2022-12-02 14:12:47.379 +0000] DEBUG (mirror-node/49 on dd64e5a2d258): [Request ID: 95e64258-c5e9-40f6-9cb9-849c8b56d7de] [GET] accounts/0x67d8d32e9bf1a9968a5ff53b87d777aa8ebbee69 200 10 ms
[2022-12-02 14:12:47.380 +0000] WARN (hbar-rate-limit/49 on dd64e5a2d258): Rate limit incoming calls, -183009120 out of 8000000000 tℏ left in relay budget until 1669990374352
[2022-12-02 14:12:47.382 +0000] TRACE (consensus-node/49 on dd64e5a2d258): [Request ID: 95e64258-c5e9-40f6-9cb9-849c8b56d7de] null eth_getTransactionCount AccountInfoQuery status: UNKNOWN (21), cost: null
[2022-12-02 14:12:47.382 +0000] ERROR (HBAR Rate limit exceeded/49 on dd64e5a2d258): [Request ID: 95e64258-c5e9-40f6-9cb9-849c8b56d7de] Error raised during getTransactionCount for address 0x67d8d32e9bf1a9968a5ff53b87d777aa8ebbee69, block number or tag pending
    code: -32606
    message: "HBAR Rate limit exceeded"
[2022-12-02 14:12:47.382 +0000] INFO (rpc-server/49 on dd64e5a2d258): [Request ID: 95e64258-c5e9-40f6-9cb9-849c8b56d7de] [POST] eth_getTransactionCount: -32606 1554 ms
```

### Steps to reproduce

1. Start up the local-node: `npx @hashgraph/hedera-local start --limits=false --dev=true`
2. Run a long test case in a hardhat project; I can work on an example test case if necessary.

### Hedera network

other

### Version

@hashgraph/hedera-local@2.3.1

### Operating system

macOS

**Comment by mshakeg** [comment] 2022-12-02 15:54
Adding a 10s sleep/delay before the relay call that usually results in this error fixes the issue, which is obviously non-ideal as it slows down dev speed.

**Comment by georgi-l95** [comment] 2022-12-02 16:19
I've opened a [PR](https://github.com/hashgraph/hedera-local-node/pull/241) , when it's merged, we're going to release a patch.

**Comment by mshakeg** [comment] 2022-12-02 21:04
@georgi-l95 great. I've also come across rate limits on eth_call which results in some of my test cases failing intermittently when running into that rate limit(even with `--limits=false`).
```
[2022-12-02 20:58:44.225 +0000] WARN (ip-rate-limit/50 on 048ddc87ea7b): Rate limit call to eth_call, 0 out of 100 calls remaining
```

**Closed** 2022-12-05 12:19 UTC
Labels: Bug

**Comment by georgi-l95** [comment] 2022-12-05 12:31
Hey @mshakeg, I'm unable to reproduce this bug with `eth_call` being rate limited. Can you check again with the new release and open issue with example, if issue still persist ?
